// <auto-generated />
using BookNest.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookNest.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251018184010_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookNest.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Political Fiction"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Human Rights"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Historical"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Name = "Autobiography"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            Name = "Thought"
                        });
                });

            modelBuilder.Entity("BookNest.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ListPrice")
                        .HasColumnType("float");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Price100")
                        .HasColumnType("float");

                    b.Property<double>("Price50")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Ghassan Kanafani",
                            CategoryId = 1,
                            Description = "A symbolic Palestinian novel that depicts the suffering of refugees and the harsh realities of displacement through a deeply human and tragic story.",
                            ISBN = "ARB1001001",
                            ListPrice = 100.0,
                            Price = 90.0,
                            Price100 = 70.0,
                            Price50 = 80.0,
                            Title = "Men in the Sun"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Abdul Rahman Munif",
                            CategoryId = 2,
                            Description = "A powerful novel exposing political oppression and human suffering in the Middle East, written with deep psychological and social insight.",
                            ISBN = "ARB2002002",
                            ListPrice = 95.0,
                            Price = 85.0,
                            Price100 = 65.0,
                            Price50 = 75.0,
                            Title = "East of the Mediterranean"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Ibrahim al-Sakran",
                            CategoryId = 5,
                            Description = "An analytical and philosophical book exploring how modern distractions affect human consciousness, faith, and culture.",
                            ISBN = "ARB4004004",
                            ListPrice = 85.0,
                            Price = 80.0,
                            Price100 = 70.0,
                            Price50 = 75.0,
                            Title = "Al-Majriyat"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Abdelwahab Elmessiri",
                            CategoryId = 4,
                            Description = "An autobiographical work that traces Elmessiri’s personal and intellectual development, offering reflections on modernity, identity, and faith.",
                            ISBN = "ARB5005005",
                            ListPrice = 120.0,
                            Price = 110.0,
                            Price100 = 90.0,
                            Price50 = 100.0,
                            Title = "My Intellectual Journey"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Muhammad Asad",
                            CategoryId = 4,
                            Description = "A captivating autobiography of a Western intellectual who embraces Islam, offering deep insights into faith, culture, and personal transformation.",
                            ISBN = "ARB6006006",
                            ListPrice = 105.0,
                            Price = 95.0,
                            Price100 = 80.0,
                            Price50 = 90.0,
                            Title = "The Road to Mecca"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Radwa Ashour",
                            CategoryId = 3,
                            Description = "A historical trilogy set in post-Reconquista Spain, telling the story of Muslims after the fall of Granada, filled with emotion, loss, and resistance.",
                            ISBN = "ARB7007007",
                            ListPrice = 130.0,
                            Price = 120.0,
                            Price100 = 100.0,
                            Price50 = 110.0,
                            Title = "Granada Trilogy"
                        });
                });

            modelBuilder.Entity("BookNest.Models.Product", b =>
                {
                    b.HasOne("BookNest.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
